### ISSUE TITLE
FileNotFoundException: Candoumbe.MiscUtilities

### ISSUE THREAD

**Issue by marcOcram** [candoumbe/DataFilters#6]
While using the extension method `StringExtensions::ToFilter(string)` it throws a `FileNotFoundException` because `Candoumbe.MiscUtilities` is missing.

```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'Candoumbe.MiscUtilities, Version=0.2.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
  Source=DataFilters
  StackTrace:
   at System.StringExtensions.ToFilter[T](StringSegment queryString) in C:\Users\ndoum\Projects\Perso\DataFilters\src\DataFilters\StringExtensions.cs:line 286
   at System.StringExtensions.ToFilter[T](String queryString) in C:\Users\ndoum\Projects\Perso\DataFilters\src\DataFilters\StringExtensions.cs:line 99
```

Issue: The NuGet reference to `Candoumbe.MiscUtilities` is missing in the dependencies.

Workaround: Install `Candoumbe.MiscUtilities` manually

**Comment by candoumbe** [comment]
Did you encounter this bug with the latest stable version ?

**Comment by marcOcram** [comment]
Yes, I have used 0.4.0
It does not list it as a dependency: https://www.nuget.org/packages/DataFilters/0.4.0

**Comment by candoumbe** [comment]
Looks like the dependency slipped between `0.3.2` and `0.4.0`.
My initial intent was to remove the explicit dependency to that package so that you were no longer required to install the `Candoumbe.MiscUtilities` package.

**Comment by candoumbe** [comment]
I'm working on a fix for the issue you submitted.
Could you download [the artifacts directory](https://github.com/candoumbe/DataFilters/suites/2598095208/artifacts/56793745) directory associated with [this run](https://github.com/candoumbe/DataFilters/runs/2452343861).
It should add `Candoumbe.MiscUtilities` back as an explicit dependency.

I should release `0.4.1` version

**Comment by candoumbe** [comment]
I just release the [0.4.1 version](https://www.nuget.org/packages/DataFilters/0.4.1) which should address this issue.
Feels free to reopen it if not solved.
