### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by marcOcram** [candoumbe/DataFilters#7]
The license information is missing.

**Comment by candoumbe** [comment]
Would `Apache 2.0` licence be ok for you ?
It suits my needs of making sure changes made to the library are available to others (that's my only requirement). I understand your initial concern about disclosing your work and I surely don't want to force anyone to disclose their work.

**Comment by candoumbe** [comment]
Starting [Datafilters 0.6.0](https://www.nuget.org/packages/DataFilters/), the library will be released under [Apache 2.0]([https://spdx.org/licenses/Apache-2.0.html
