### ISSUE TITLE
Support case-insensitive property search

### ISSUE THREAD

**Issue by marcOcram** [candoumbe/DataFilters#8]
If I have a model like the following and apply the query `id=1` it does not find the property `ID`.

```csharp
public class Model {
    public int ID { get; set; }
}
```

```csharp
IFilter filter = "id=1".ToFilter<Model>(); // evaluates to {"field":null,"op":"isnull"} instead of {"field":"ID","op":"eq","value":"1"}
```

**Comment by candoumbe** [comment]
I'll have a look a this issue.
Did you try the latest stable version ?

**Comment by marcOcram** [comment]
I used version 0.4.0.

I think the issue is here where you do a case-sensitive search. A configuration would be useful to alter the behavior.
https://github.com/candoumbe/DataFilters/blob/722a70fbadf1972b7603e07c578b074ad704cba2/src/DataFilters/StringExtensions.cs#L257-L258

**Comment by candoumbe** [comment]
Good point !!!
I will fix this in the next release. In the meantime, you can use the `{nameof(Model.ID)}=<value>` which should always be accurate.

I think it's a valid point to make the search case insensitive. I'm also thinking about ways to handle more transformation (from/to snake_case, kebab-case and so on ...)

**Comment by candoumbe** [comment]
Ok so here is some insights on what this feature could look like :

- introduction of a `PropertyNameResolutionStrategy` class : this is the base class for altering the way the property search works :

```csharp
namespace DataFilters.Casing
{
    /// <summary>
    /// <para>
    /// Base class to derive from to alter the way <see cref="System.StringExtensions.ToFilter{T}(string)"/>
    /// and <see cref="System.StringExtensions.ToSort{T}(string)"/> performs property names lookup.
    /// </para>
    /// </summary>
    public abstract class PropertyNameResolutionStrategy
    {
        public abstract string Handle(string name);
    }
}
```

-  new overload for `StringExtensions.ToFilter<T>(string input, PropertyNameResolutionStrategy propertyNameResolutionStrategy)`

This way you could have a custom implementation to suit your needs.

This feature would be available with 3 implementations : `CamelCasePropertyNameResolution`, `SnakeCasePropertyNameResolution` and `DefaultPropertyNameResolution`.

I'm still working on the feature as this would also require to add the same overloads for `StringExtensions.ToSort<T>()`

**Comment by candoumbe** [comment]
The [0.5.0](https://www.nuget.org/packages/DataFilters/0.5.0) released today should help you solved the issue you submitted.
Let me know if it worked as you expect.

**Comment by marcOcram** [comment]
As of your new license I am not able to use/test your library in any way. Nevertheless the change looks good but I would have chosen an interface instead of an abstract class.

**Comment by candoumbe** [comment]
The idea of the licence is to make sure any changes made to a fork is made available to others.
You're still free to use the package in a commercial product. If that's not the case, I can switch to LGPL (or even considering MIT licence). I'm not an expert in copyright stuff in any way 😅.

About the new `PropertyNameResolutionStrategy` class, you're right : it's indeed an interface as it has only 1 method.
